version: '3'
services:
  web:
    image: docker-express
    build: ./app
    command: nodemon server.js
    ports:
      - '3000:3000'
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - 'mongo'

  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'

  adminmongo:
    image: 'mrvautin/adminmongo'
    ports:
      - '1234:1234'
    environment:
      - 'HOST=0.0.0.0'
